name = "riddick-crate-processor"
main = "src/index.ts"
compatibility_date = "2025-07-05"

[[queues.consumers]]
queue = "crate-processing"
max_batch_size = 1
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "crate-processing-dlq"

[[queues.producers]]
binding = "PARSE_QUEUE"
queue = "crate-parsing"

[[queues.producers]]
binding = "CRATE_QUEUE"
queue = "crate-processing"

[[d1_databases]]
binding = "DB"
database_name = "riddick-db"
database_id = "local"
migrations_dir = "../migrations"

[[r2_buckets]]
binding = "CRATES_STORAGE"
bucket_name = "riddick-crates"


# [env.production]
# name = "riddick-crate-processor-production"

# [[env.production.queues.consumers]]
# queue = "crate-processing"
# max_batch_size = 1
# max_batch_timeout = 30
# max_retries = 3
# dead_letter_queue = "crate-processing-dlq"

# [[env.production.queues.producers]]
# binding = "CRATE_QUEUE"
# queue = "crate-processing"

# [[env.production.d1_databases]]
# binding = "DB"
# database_name = "riddick-db-production"
# database_id = "57929bff-19f7-4bf3-aa36-2832694793dc"
# migrations_dir = "../migrations"

# [[env.production.r2_buckets]]
# binding = "CRATES_STORAGE"
# bucket_name = "riddick-crates-production"

# [env.production.vars]
# CRATES_API_BASE_URL = "https://crates.io/api/v1"

[observability.logs]
enabled = true
