name = "riddick"
main = "src/index.ts"
compatibility_date = "2025-07-05"


[[d1_databases]]
binding = "DB"
database_name = "riddick-db"
database_id = "local"
migrations_dir = "migrations"

[env.production]
name = "riddick-production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "riddick-db-production"
database_id = "production"
migrations_dir = "migrations"
