name = "rust-parser-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2025-07-12"

[build]
command = "cargo install -q worker-build && worker-build --release"


[[queues.consumers]]
queue = "crate-parsing"
max_batch_size = 1
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "crate-parsing-dlq"

[[queues.producers]]
binding = "parse_queue"
queue = "crate-parsing"

[[d1_databases]]
binding = "db"
database_name = "riddick-db"
database_id = "local"
migrations_dir = "../migrations"

[[r2_buckets]]
binding = "CRATES_STORAGE"
bucket_name = "riddick-crates"
