// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemInfo } from "./ItemInfo";

export type AdtDetails = { adtType: string, methods: Array<ItemInfo>, };
