// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModuleInfo } from "./ModuleInfo";

export type CrateInfo = { name: string, modules: Array<ModuleInfo>, rootModule: ModuleInfo, };
