// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemInfo } from "./ItemInfo";
import type { ModuleReference } from "./ModuleReference";

export type FileInfo = { items: Array<ItemInfo>, moduleReferences: Array<ModuleReference>, };
