// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdtDetails } from "./AdtDetails";
import type { FunctionDetails } from "./FunctionDetails";
import type { ModuleDetails } from "./ModuleDetails";
import type { OtherDetails } from "./OtherDetails";
import type { TraitDetails } from "./TraitDetails";

export type ItemDetails = { "function": FunctionDetails } | { "adt": AdtDetails } | { "trait": TraitDetails } | { "module": ModuleDetails } | { "other": OtherDetails };
