// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemDetails } from "./ItemDetails";

export type ItemInfo = { name: string, fullCode: string, docComment: string | null, visibility: string, location: [number, number], details: ItemDetails, };
