// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldInfo } from "./FieldInfo";
import type { ParameterInfo } from "./ParameterInfo";
import type { SourceLocation } from "./SourceLocation";
import type { VariantInfo } from "./VariantInfo";

export type ItemInfo = { type: string, name: string, visibility: string, location: SourceLocation, sourceCode: string, attributes: Array<string>, genericParameters: Array<string>, parameters: Array<ParameterInfo> | null, returnType: string | null, fields: Array<FieldInfo> | null, variants: Array<VariantInfo> | null, implType: string | null, traitName: string | null, };
