// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemInfo } from "./ItemInfo";
import type { SourceLocation } from "./SourceLocation";

export type ModuleInfo = { name: string, path: string, items: Array<ItemInfo>, location: SourceLocation, };
