// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModuleReference = { name: string, visibility: string, expectedPaths: Array<string>, location: [number, number], };
