// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileInfo } from "./FileInfo";
import type { ParseError } from "./ParseError";

export type ParseResponse = { success: boolean, parseTime: bigint, fileInfo: FileInfo | null, errors: Array<ParseError>, };
