// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrateInfo } from "./CrateInfo";
import type { ParseError } from "./ParseError";

export type ParseResponse = { success: boolean, parseTime: bigint, crateInfo: CrateInfo | null, errors: Array<ParseError>, };
