// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TraitMethodInfo } from "./TraitMethodInfo";

export type TraitDetails = { methods: Array<TraitMethodInfo>, };
